name: publish

on:
  release:
    types: [ published ]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Jar
        run: ./gradlew --no-daemon --refresh-dependencies clean distTar
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: ${{ github.run_id }}
          path: build/distributions/rbac.tar

  app-image:
    runs-on: ubuntu-latest
    needs: build-app
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Pull cache
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_id }}
          path: build/distributions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/wyaaung/role-based-access-contro
          tags: type=raw,${{ github.event.release.tag_name }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: deployment/app/Dockerfile
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
